### ISSUE TITLE
Ordering Groups VariableA

### ISSUE THREAD

**Issue by alehsierra** [microsud/microbiomeutilities#117]
Hello,
I am having an issue with the order of the VariableA plotted, any way to group all variables in one side?

Thanks,

Maria.

[Cladonia.heat.pdf](https://github.com/microsud/microbiomeutilities/files/2833071/Cladonia.heat.pdf)

**Comment by microsud** [comment]
Hi! 
Thanks for the query. You could try adding `cluster_cols = FALSE` in the command for `plot_taxa_heatmap`. If it does not work then another way would be to order the samples in metadata files in the begining.

Let me know if it works.
Cheers,
Sudarshan

**Comment by microsud** [comment]
Hi,
Sorry, my apologies. I wanted to say `cluster_rows`. You can probably check `pheatmap` as `plot_taxa_heatmap` function only makes phyloseq object accessible to this function. and you can add pheatmap options to this command. 
Let me know if this works.

**Comment by microsud** [comment]
Hi @alehsierra 
I will close this issue for now. Feel free to reopen this issue if you still face issues with the function.
Alternative way of heatmap visualisation can be found on this tutorial page [tutorial page](https://mibwurrepo.github.io/Microbial-bioinformatics-introductory-course-Material-2018/introduction.html)

Best wishes,
Sudarshan
