### ISSUE TITLE
White grid in plot_taxa_heatmap

### ISSUE THREAD

**Issue by adamsorbie** [microsud/microbiomeutilities#130]
Hi, 

I can't seem to figure out why but when using the plot_taxa_heatmap function, it always returns a heatmap with each cell separated by a small white border. I guess there is some setting which can be passed to pheatmap to alter this behaviour but I can't find out which. Do you have any idea? I attached an example of the output. 
![Rplot](https://user-images.githubusercontent.com/23216921/92753070-cdf9f100-f389-11ea-85de-5138a818ec45.jpeg)

**Comment by microsud** [comment]
@adamsorbie It is specified within the function. I will update the pkg to remove it then you can try by specifying `border_color = NA` within the function `plot_taxa_heatmap`.

Best wishes,
Sudarshan

**Comment by adamsorbie** [comment]
Thanks a lot!
