### ISSUE TITLE
Update readme and website

### ISSUE THREAD

**Issue by microsud** [microsud/microbiomeutilities#151]
Suggest one citation for both `microbiome` and `microbiomeutilities` as a part of the `microbiome-verse` idea?
Link pkg website with main page for `microbiome`
@antagomir thoughts?

**Comment by antagomir** [comment]
Sure. My main concern is how to allocate the scope of the different packages so that we have a few nicely complementary ones instead of five similar packages. For the time being we can just cite all included packages but let's consider this also.
