### ISSUE TITLE
get_group_abundances group argument without NULL as default

### ISSUE THREAD

**Issue by phauxfiniks** [microsud/microbiomeutilities#160]
Hi, when running get_group_abundances, the default of "group" is NULL as stated in the documentation. However, if this argument was left missing, an error of `argument "group" is missing, with no default` could be seen. Is it a bug with the package?

Thank you!

**Comment by microsud** [comment]
Thank you for point this out. I will improve the documentation for this and maybe change the default. In case you do not want abundance values by group, you can try [taxa_summary](https://microsud.github.io/microbiomeutilities/articles/microbiomeutilities.html#get-taxa-summary). Hope this helps.

Best wishes,
Sudarshan
