### ISSUE TITLE
heatmap

### ISSUE THREAD

**Issue by najibveto** [microsud/microbiomeutilities#166]
hello, I would like to ask your help if possible.
I used the microbiomeutilities to generate a heatmap from my biom file and I go the species of my otu.
is there isn't any other way to specify which taxa-level to plot as heat map?.
also is possible to omit the prevalence function?
thank you for your help.
I attached the map I generated.

**Comment by microsud** [comment]
Thanks for the query. Which function did you use ? and I don't see the attached heat map 😉

**Comment by najibveto** [comment]
thanks, I use the plot_taxa_heatmap. sorry, i forgot to attach the heat map.
![Rplot28](https://user-images.githubusercontent.com/77666435/105014836-3e292980-5a84-11eb-9ad6-e3c540bccf1f.jpeg)

**Comment by microsud** [comment]
It is not possible at the moment. I need to re-write this function and need time for it. 
For the other part, you can make a phyloseq object at the level you want and provide it as input. 
Try `ps.family <- aggregate_taxa(ps0, "Family")` to get family level data and use it as input for plotting.

**Comment by najibveto** [comment]
thanks for your answer. I tried your suggested solution and I got the desired results. 
the code I used as below.
I am curious about the use of gsub as in my taxa labeling I don't have the d__denovo, is it possible to omit it? also the label in the plot show two time the family name.
for species, I have only the species names. how to merge genus and species column?
sorry for the trouble. 
library(microbiomeutilities)
library(microbiome)
library(knitr)
library(tibble)
library(dplyr)
library(pheatmap)
library(RColorBrewer)
ps = import_biom("RiceOTUN150kp1cleanaddOther.biom", treefilename="RiceOTUreduced.tre", parseFunction= parse_taxonomy_greengenes)
ps
ps.family <- aggregate_taxa(ps, "Family")
taxa_names(ps.family) <- gsub("d__denovo", "OTU:", taxa_names(ps.family))
grad_ab <- colorRampPalette(c("#faf3dd","#f7d486" ,"#5e6472"))
grad_ab_pal <- grad_ab(10)
gray_grad <- colorRampPalette(c("white", "steelblue"))
gray_grad_cols <- gray_grad(10)

meta_colors <- list(c("Odae" = "#FFC857", 
                      "Ilpoom" = "#05B083"), 
                    c("Hull" = "steelblue", 
                      "BrownRice" = "grey50", 
                      "WhiteRice"="brown3"),
                    gray_grad_cols)
names(meta_colors) <- c("cultivar", "Tissue")
p <- plot_taxa_heatmap(ps,
                       subset.top = 25,
                       VariableA = c("cultivar","Tissue"),
                       heatcolors = grad_ab_pal, #rev(brewer.pal(6, "RdPu")),
                       transformation = "log10",
                       cluster_rows = T,
                       cluster_cols = F,
                       show_colnames = F,
                       annotation_colors=meta_colors)

**Comment by microsud** [comment]
Good. I also removed the `prevalence` option from the plot in latest v1.00.13. For `gsub` check this primer on the parent `microbiome` R package [website](https://microbiome.github.io/tutorials/cleaning_taxonomy_table.html). The duplicate labelling is because you add it with `gsub`. You can skip it. For merging genus+species, I am not sure how your species column looks like and therefore cannot provide a direct solution. You should be able to find a solution online. If you do, please post it here for others :)

**Comment by najibveto** [comment]
thanks a lot. for the gsub, I omitted but still give double name. the taxa table is as follow (kable(head(tax_table(ps))[3:6])):
![image](https://user-images.githubusercontent.com/77666435/105152807-01743580-5b4b-11eb-9544-b79c36b3fbfa.png).

**Comment by microsud** [comment]
Try this to merge genus.species
```
library(tibble)
library(dplyr)
tax_tb <- as(tax_table(ps),"matrix") %>% 
  as.data.frame() %>% 
  rownames_to_column("ASV") %>% 
  mutate(Genus.Species = ifelse(!is.na(Species), paste0(Genus, ".", Species), Species)) %>% 
  select(-Species)   %>% 
rename(Species = Genus.Species)

#tax_tb[1:30, 5:9]
rownames(tax_tb) <- tax_tb$ASV
tax_tb <- tax_tb[,-1]

tax_table(ps) <- tax_table(as.matrix(tax_tb))
```

**Comment by najibveto** [comment]
really I don't know what to say, thank you a lot for your help. sorry for trouble.

**Comment by najibveto** [comment]
thank you a lot for your help. one question if possible, the order in heatmap is fixed based on what? if I want the most abundant to be on the first row, should i modify the function?
