### ISSUE TITLE
Error with plot_taxa_cv()

### ISSUE THREAD

**Issue by elaine-shen** [microsud/microbiomeutilities#169]
Hello,

Thanks for a great package! I am running into this error when attempting to run `plot_taxa_cv()` on my phyloseq object:

Here is my phyloseq information:
`> merged_phyloseq_80
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 32450 taxa and 69 samples ]
sample_data() Sample Data:       [ 69 samples by 10 sample variables ]
tax_table()   Taxonomy Table:    [ 32450 taxa by 9 taxonomic ranks ]`

Here is the error:
`> p1 <- plot_taxa_cv(merged_phyloseq_80, plot.type = "scatter")
Error: Problem with `mutate()` input `MeanAbun`.
x Input `MeanAbun` can't be recycled to size 32450.
ℹ Input `MeanAbun` is `x.mean.rel`.
ℹ Input `MeanAbun` must be size 32450 or 1, not 69.`

Here is the error in more detail: 
`├─<error/dplyr:::mutate_error>
│ Problem with `mutate()` input `MeanAbun`.
│ x Input `MeanAbun` can't be recycled to size 32450.
│ ℹ Input `MeanAbun` is `x.mean.rel`.
│ ℹ Input `MeanAbun` must be size 32450 or 1, not 69.
└─<error/dplyr:::mutate_incompatible_size>
Backtrace:
    █
 1. ├─microbiomeutilities::plot_taxa_cv(merged_phyloseq_80, plot.type = "scatter")
 2. │ └─`%>%`(...)
 3. ├─dplyr::mutate(., MeanAbun = x.mean.rel, CV = x.cvs)
 4. ├─dplyr:::mutate.data.frame(., MeanAbun = x.mean.rel, CV = x.cvs)
 5. │ └─dplyr:::mutate_cols(.data, ...)
 6. │   ├─base::withCallingHandlers(...)
 7. │   └─mask$eval_all_mutate(quo)
 8. └─dplyr:::abort_glue(character(0), list(x_size = 69L), "dplyr:::mutate_incompatible_size")
 9.   └─rlang::exec(abort, class = class, !!!data)`

Please let me know if there is something wrong with my phyloseq object that is causing this error - I'm not sure I am catching it if that's the case. The example with the zackular2014 works fine.

**Comment by microsud** [comment]
Hi @elaine-shen Thanks for raising this issue. What is the output of `taxa_are_rows(merged_phyloseq_80)` ? If it is *FALSE* then you need to transpose the `otu_table`. 
```
otu_tb <- microbiome::abundances(merged_phyloseq_80) # this will convert OTU to rows and samples to columns
otu_table(merged_phyloseq_80) <- otu_table(otu_tb, taxa_are_rows = T)

# check if the value of this is TRUE
taxa_are_rows(merged_phyloseq_80)

# then plot 
p1 <- plot_taxa_cv(merged_phyloseq_80, plot.type = "scatter")
```
Let me know if this works.

**Comment by microsud** [comment]
This can now be internally resolved by `plot_taxa_cv` in the latest version 1.00.15

Please close the issue if this fix has resolved the error.

**Comment by elaine-shen** [comment]
Thanks for the help! Yes, the error has been resolved.
