### ISSUE TITLE
Cannot install microbiomeutilities on R, what to do?

### ISSUE THREAD

**Issue by tcrispino13** [microsud/microbiomeutilities#171]
Hello, Ive been trying to install the microbiomeutilities in R but I cannot do it due to some errors. I am new to bioinformatics and I really need help on this. Thank you so much!

**Comment by microsud** [comment]
To assit you better, please provide more information. How did you try to install? Which OS win/Linux/Mac? What was the (some) error?

**Comment by tcrispino13** [comment]
Ive been trying to install it in R, my OS is Windows 10. Here are some of the errors: 
Error: Failed to install 'microbiomeutilities' from GitHub:
  (converted from warning) packages ‘dplyr’, ‘tibble’, ‘tidyr’ are in use and will not be installed
  
 I think it has some issues with the other packages I have in R. Thanks!

**Comment by microsud** [comment]
Thanks! The warnings suggest that you have an active session with different packages loaded. Please **restart** R and install again. Let me know it works.

**Comment by tcrispino13** [comment]
Hello, I tried to do your suggestion. I still cannot install it. Here's the error:
Error: Failed to install 'microbiomeutilities' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘data.table’

**Comment by microsud** [comment]
You can search online for resolving this issue and try installing again. https://stackoverflow.com/questions/45922418/error-in-install-packages-cannot-remove-prior-installation-of-package-dbi/51482733

**Comment by tcrispino13** [comment]
I already solved the issue. Thanks for your help!
