### ISSUE TITLE
rlang::last_error()

### ISSUE THREAD

**Issue by JunqiangZheng** [microsud/microbiomeutilities#172]
> pn_phylum <- plot_taxa_boxplot(phy,
+                         taxonomic.level = "Phylum",
+                         top.otu = 10, group = "treatment",
+                         title = "Rel plot", group.colors = "Set2")
The phy_tree slot is empty, easy to make the plot
错误: More than one expression parsed
Run `rlang::last_error()` to see where the error occurred.

**Comment by microsud** [comment]
Hi @JunqiangZheng 
Thanks for the issue. However, it is not informative for me to help you. Can you please provide as much detail as possible? Does the function work with test data from the package? Can you provide an example that reproduces the error you get?

Best regards,
Sudarshan

**Comment by kabanowa47** [comment]
I saw the same a couple of minutes ago. The working solution in my case was indeed only changing characters to factors in metadata. I hope this can help someone. And many thanks for your package!
`ps@sam_data$my_group <- as.factor(ps@sam_data$my_group)`

**Comment by microsud** [comment]
Thanks!
