### ISSUE TITLE
Phy_tree not included in the result of format_to_besthit

### ISSUE THREAD

**Issue by tcrispino13** [microsud/microbiomeutilities#173]
Is there a way to include the phy_tree in the phyloseq object after using the format_to_besthit function? Ive been following this commands and I need to measure the unifrac distances based on the phylogenetic tree but after using the format_to_besthit, it turns out the phy_tree was not included.

ps2 <- tax_glom(ps, "genus")
ps2f <- format_to_besthit(ps)
orddi <- ordinate(ps2f, method = "PCoA", distance = "unifrac", weighted= FALSE)
Error in access(physeq, "phy_tree", errorIfNULL) :
phy_tree slot is empty.

**Comment by microsud** [comment]
Hi @tcrispino13 Thanks for pointing this out. I will try to work on this when I have time, hopefully sometime this week or later next week. 

Best wishes,
Sudarshan

**Comment by microsud** [comment]
This is now fixed in #174 I will close the issue here.
