### ISSUE TITLE
Relative abundance plot for selected taxa 

### ISSUE THREAD

**Issue by shigdel** [microsud/microbiomeutilities#175]
i tried to use  code from microbiomeutilites package to make a relative abundance plot for selected taxa across different groups  but the code doesn't work , even i tried to rerun your code using your example data 
<img width="947" alt="E" src="https://user-images.githubusercontent.com/86776588/124109404-62435a80-da67-11eb-99aa-19ebb657055e.png">

**Comment by microsud** [comment]
I tested this now and I am unable to reproduce the error. Are you using the following versions of the `microbiome` (1.12.0) and `microbiomeutilties` (1.00.16) pkg?

**Comment by shigdel** [comment]
microbiomeutilities_1.00.11, and microbiome_1.12.0

**Comment by microsud** [comment]
Thanks. Can you update to the latest version of `micorbiomeutilities` and see if there is error?

**Comment by shigdel** [comment]
yes i did now it works , thank you so much :)

**Comment by microsud** [comment]
great!
