### ISSUE TITLE
Taxonomic levels should be either 6 (untill genus) or 7 (until species) level

### ISSUE THREAD

**Issue by tarunaaggarwal** [microsud/microbiomeutilities#176]
Hello,

I'm working with 16S data, and have an additional domain column in my tax_table of my phyloseq object. Is there any way I can still make boxplots for specific taxa using your package? 

My phyloseq object info:
`phyloseq-class experiment-level object`
`otu_table()   OTU Table:         [ 15 taxa and 14 samples ]`
`sample_data() Sample Data:       [ 14 samples by 19 sample variables ]`
`tax_table()   Taxonomy Table:    [ 15 taxa by 8 taxonomic ranks ]`

And specific code I'm trying to use:
`p0 <- phy_prune_pa_exp_noChloro_noMito_f__OM190`
  `p0.f <- format_to_besthit(p0)`
 ` select.taxa <- c("f__OM190")`
  `mycols <- c("brown3", "steelblue")`
  `p <- plot_listed_taxa(p0, select.taxa,
                        group = "treatment",
                        add.violin = TRUE,
                        group.colors = mycols
  )`

**Comment by microsud** [comment]
You can try to remove the domain column as below and the plot:
```
tax_table(p0) <- tax_table(p0)[,-1]
print(p0)
p <- plot_listed_taxa(p0, select.taxa, group = "treatment", add.violin = TRUE, group.colors = mycols )
```

Cheers,
Sudarshan
