### ISSUE TITLE
Problem to install

### ISSUE THREAD

**Issue by Fuad59** [microsud/microbiomeutilities#177]
Hi,
how can I download a zip file of microbiomeutilities 1.00.15 for manually installation?
I used devtools::install_github("microsud/microbiomeutilities")
but it failed saying "~/microbiomeutilities_1.00.16.tar.gz’ had non-zero exit status".
Thank you.
Fuad

**Comment by microsud** [comment]
Any specific reason why you prefer this 1.00.15 version? I did not make a release for this version. The command you showed here will download the main latest version. 
Can you share the error in more detail?

**Comment by Fuad59** [comment]
I want to add reference sequence using add_refseq to my saved phyloseq object file. So, I can run the phyloseq object for functional annotation and prediction using Tax4Fun2.
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'phyloseq' in library.dynam(lib, package, package.lib):
 DLL 'igraph' not found: maybe not installed for this architecture?
Error : package 'phyloseq' could not be loaded
Error: loading failed
Execution halted
*** arch - x64
Warning: package 'microbiome' was built under R version 4.1.1
Warning: package 'ggplot2' was built under R version 4.0.5
Warning: package 'dplyr' was built under R version 4.0.5
Warning: replacing previous import 'ggplot2::alpha' by 'microbiome::alpha' when loading 'microbiomeutilities'
ERROR: loading failed for 'i386'
* removing 'C:/Users/forest/Documents/R/win-library/4.0/microbiomeutilities'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/forest/AppData/Local/Temp/Rtmp8capCw/filee440682e1292/microbiomeutilities_1.00.16.tar.gz’ had non-zero exit status.
Maybe it's a specific lib directory problem of my settings. So, if you can provide me the zip file, then I can have a try to check.

**Comment by microsud** [comment]
The issue seems to be with igraph pkg. You need to make sure that igraph and phyloseq are installed first. I can try to make the source of my package tomorrow. However it may not solve the issue.

**Comment by Fuad59** [comment]
I am already using igraph and phyloseq. I think maybe it's a problem with R version.

**Comment by microsud** [comment]
Here is the source for the package
[microbiomeutilities_1.00.16.tar.gz](https://github.com/microsud/microbiomeutilities/files/7839540/microbiomeutilities_1.00.16.tar.gz)

**Comment by Fuad59** [comment]
thank you.
