### ISSUE TITLE
Error in `check_aesthetics()`: ! plot_ordination_utils

### ISSUE THREAD

**Issue by imonteroo** [microsud/microbiomeutilities#178]
I am trying with my own phyloseq object (that works with plot_ordination) but when I try :+1: 

`nmordinationbray = ordinate(ps_aa, method="NMDS", distance = "bray")
plot_ordination_utils(ps_aa, nmordinationbray, color = "group", plot.arrow = TRUE, scale.arrow = NULL, top.taxa = 5)`

I receive:

`Error in `check_aesthetics()`:
! Aesthetics must be either length 1 or the same as the data (1): xend and yend
Run `rlang::last_error()` to see where the error occurred.`

**Comment by imonteroo** [comment]
I fix it by adding `format_to_besthit()` function before `ordinate()`, but I would like to change the arrow labels, they are all the taxonomy form kingdom to species.

**Comment by microsud** [comment]
This somehow missed my attention. My Apologies. 
For future reference I suggest checking the microViz package for high level functionality for ordination plots.
https://david-barnett.github.io/microViz/articles/web-only/ordination.html

Best wishes,
Sudarshan
