### ISSUE TITLE
plot_taxa_barplot - 

### ISSUE THREAD

**Issue by mariamaseng** [microsud/microbiomeutilities#179]
Hi! I am using the function plot_taxa_barplot and got a question; the input data is as counts, but on the y-axis of the plot it says "relative abundance %". My output shows that I got several at 100% and of that I am surprised. Should I transform my data prior input? THis only applies to genus level data, not e.g phylum level.

![image](https://user-images.githubusercontent.com/66627015/186205463-16450dd3-ca10-497f-ac2e-0c250598008e.png)

Thanks!

**Comment by microsud** [comment]
Hi! Does this happen with the example data? If not then could you provide a reproducible example? This will help in finding the cause of the issue.
Cheers,
Sudarshan

**Comment by mariamaseng** [comment]
I don't know, but should it in theory be ok that I do aggregate_taxa to genus level and then keep the input data as counts?

**Comment by microsud** [comment]
Difficult to guesswork. I guess you are using plot_listed_taxa and not plot_taxa_barplot?
The former function converts counts to relative abundance internally before plotting.
Input counts -> plot relative abundance 

Secondly if you can share your codes I can investigate. 
In anycase, on your genus level data you can check how many genera are detected. Check richness function in microbiome r package which will return observed genera per sample. If you find samples with only one or few genus then you know if there is a  issue of mono dominance.

**Comment by mariamaseng** [comment]
Ok, thanks a lot for your rapid response. Thanks, that clarified what I wondered about. Yes, I will check that. Thanks :)
