### ISSUE TITLE
Taxonomic_Levels Percent_Classification

### ISSUE THREAD

**Issue by apoosakkannu** [microsud/microbiomeutilities#183]
Hi, 
I am trying to identify my dataset taxonomic resolution using microbiomeutilities package. I found a small problem in calculation. The domain and Phylum percent classification should be 100% in my dataset. But I get the following.

##upload required libraries
library(phyloseq)
library(file2meco)
library(microbiomeutilities)
library(ggplot2)

#taxonomy resolution calculation
percent_classified(pseq)

##output 
Taxonomic_Levels Percent_Classification
1           Domain              99.9998 %
2           Phylum              99.9998 %
3            Class              99.9442 %
4            Order              99.7169 %
5           Family              98.2093 %
6            Genus              94.0961 %
7          Species              59.1211 %
8        OTUs/ASVs                 438997

Could you kindly provide me the reason or any correction needed? I have attached my dataset for your reference. 
[physeq.rds.zip](https://github.com/microsud/microbiomeutilities/files/10073396/physeq.rds.zip)

**Comment by microsud** [comment]
Thanks for using our tool and reporting this bug. I have fixed this bug and it should be visible in a few minutes in the main branch with the latest version 1.00.17.

**Comment by apoosakkannu** [comment]
thanks for for your swift response. It worked after reinstalling the package.
